server:
  port: 8030
spring:
  application:
    name: gatway
eureka:
  client:
    service-url:
      deafultZone: http://localhost:8761/eureka/
ribbon:
  ConnectTimeout:  50000
  ReadTimeout:  50000
  eager-load:
    enabled: true
  eureka:
    enabled: true
zuul:
  routes:
    provider: /p/**
    #给服务提供者 provider 设置映射
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000